version: "3"
services:

  external-service:
    image: php:7.1.31-cli-alpine
    container_name: circuitbreaker_external-service
    ports:
      - 1234:80
    volumes:
      - ./external-service/:/var/www/html/
    working_dir: /var/www/html/
    command: php -S 0.0.0.0:80 index.php

  prometheus:
    image: prom/prometheus
    container_name: circuitbreaker_prometheus
    network_mode: "host"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: circuitbreaker_grafana
    network_mode: "host"