version: "3"
services:

  external-service:
    build:
      context: ./docker/wiremock
      dockerfile: Dockerfile-wiremock
    image: wiremock:latest
    container_name: circuitbreaker_external-service
    ports:
      - 1234:8080
    volumes:
      - ./wiremock/:/home/wiremock/

  prometheus:
    image: prom/prometheus
    container_name: circuitbreaker_prometheus
    network_mode: "host"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: circuitbreaker_grafana
    network_mode: "host"
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
      - ./docker/grafana/dashboards/:/var/lib/grafana/dashboards/