global:
  scrape_interval: 15s

  external_labels:
    monitor: 'circuit-breaker-monitor'

scrape_configs:
  # - job_name: 'prometheus'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:8080']

  - job_name: 'circuit-breaker-metrics'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['localhost:8080']